# Generated by Django 6.0.6 on 2026-07-11 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_term_months',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='ml_probability_score',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='purpose',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly applicant income', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coapplicant_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly co-applicant income', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='ML model confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_history',
            field=models.FloatField(blank=True, help_text='Credit history score (1.0 for good, 0.0 for bad)', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='debt_ratio',
            field=models.FloatField(blank=True, help_text='Debt-to-income ratio', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='dependents',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3+', '3+')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], default='Graduate', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='existing_loans',
            field=models.IntegerField(default=0, help_text='Number of existing active loans'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_amount_term',
            field=models.IntegerField(default=360, help_text='Term of loan in months'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='married',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='prediction',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], help_text='ML model decision', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='property_area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Semiurban', 'Semiurban'), ('Rural', 'Rural')], default='Urban', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total savings amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='self_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Loan amount requested', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20),
        ),
    ]
