# Generated by Django 6.0.6 on 2026-07-11 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('personal', 'Personal Loan'), ('education', 'Education Loan'), ('car', 'Car Loan'), ('business', 'Business Loan')], default='home', max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in %', max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Processing fee in INR', max_digits=10)),
                ('minimum_income', models.DecimalField(decimal_places=2, default=25000.0, help_text='Minimum monthly income required (INR)', max_digits=12)),
                ('minimum_credit_score', models.IntegerField(default=650)),
                ('maximum_loan_amount', models.DecimalField(decimal_places=2, default=10000000.0, help_text='Maximum loan amount in INR', max_digits=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Offering',
                'verbose_name_plural': 'Bank Offerings',
                'ordering': ['bank_name', 'interest_rate'],
            },
        ),
    ]
