# Generated by Django 6.0.6 on 2026-07-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('rewards', 'Rewards'), ('travel', 'Travel'), ('cashback', 'Cashback'), ('student', 'Student'), ('business', 'Business')], max_length=20)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('min_credit_score_required', models.IntegerField(default=600)),
                ('features', models.JSONField(default=list, help_text='List of card features')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='cards.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ml_probability_score', models.FloatField(blank=True, help_text='Probability score from ML model (0-1)', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cards.creditcard')),
            ],
        ),
    ]
