# Generated by Django 6.0.6 on 2026-07-11 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='bank',
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['bank_name', 'card_name'], 'verbose_name': 'Credit Card', 'verbose_name_plural': 'Credit Cards'},
        ),
        migrations.AlterModelOptions(
            name='creditcardapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Credit Card Application', 'verbose_name_plural': 'Credit Card Applications'},
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='features',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='min_credit_score_required',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='creditcardapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='creditcardapplication',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='creditcardapplication',
            name='ml_probability_score',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='bank_name',
            field=models.CharField(default='Partner Bank', max_length=255),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of structured benefits or bullet points'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_name',
            field=models.CharField(default='Standard Card', max_length=255),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('cashback', 'Cashback'), ('rewards', 'Rewards'), ('student', 'Student'), ('business', 'Business'), ('premium', 'Premium')], default='rewards', max_length=50),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='image',
            field=models.URLField(blank=True, help_text='Card image URL', null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to hide card from catalog without deleting historical applications'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='joining_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='minimum_credit_score',
            field=models.IntegerField(default=650),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='minimum_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum annual income required', max_digits=12),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='reward_type',
            field=models.CharField(blank=True, help_text='e.g., Cashback, Reward Points, Air Miles', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Applicant annual income', max_digits=12),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='bank_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='ML model confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], default='employed', max_length=30),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='existing_credit_cards',
            field=models.IntegerField(default=0, help_text='Number of existing credit cards held'),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='monthly_housing_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='prediction',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], help_text='ML predicted outcome', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='selected_credit_card',
            field=models.ForeignKey(blank=True, help_text='Target credit card (null if applying for general recommendation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cards.creditcard'),
        ),
        migrations.AddField(
            model_name='creditcardapplication',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total current debt', max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcardapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
